// Generated by https://quicktype.io

import {Usuario} from "../pages/interface/usuario";

export interface Game {
  name: string;
  id: string;
  url: string;
  votos: number;
}


export const GAMES:Game[] = [
  //LOS USUARIOS DEBEN TENER SUS PASSWORDS CIFRADAS
  {id: "cyberpunk-2077", name: "Cyberpunk 2077", url:"https://gaming-cdn.com/images/products/840/616x353/cyberpunk-2077-pc-juego-gog-com-cover.jpg?v=1663862900", votos: 41},
  {name: 'Death Stranding', id: 'death-stranding', url: 'https://cdn1.epicgames.com/f4a904fcef2447439c35c4e6457f3027/offer/DS_wide-2560x1440-c3d7bbf8ee36dd025610088381a5235a.jpg', votos: 35},
  {id: 'smasch-utimate', url: 'https://i.blogs.es/87950a/super-smash-bros-ultimate/840_560.jpg', name: 'Smasch Bros Ultimate', votos: 37},
  {name: 'Zelda - BOTW', id: 'zelda-botw', url: 'https://i.blogs.es/15da49/zelda00/1366_2000.jpg', votos: 34}
];
